### ISSUE TITLE
[Bug] Items don't exit through the portal hole

### ISSUE THREAD

**Issue by vizthex123** [SuperMartijn642/Wormhole#28] opened 2022-06-18 07:11 UTC
**Version Info**
- Minecraft, 1.18.2
- Wormhole: 1.1.9b

**Description of the Bug**
I noticed that items teleport 2 - 3 blocks in front of the portal frame, rather than being dropped directly in fronto f the "portal hole" where those blocks would be.

This means that vertical portals for item transport don't work as well as they should, which is a bit annoying.

**Steps to Reproduce**
1) Build 2 portals within view range of each other
2) Connect them
3) Toss in some items and see how they land a few blocks in front of the portal structure

**Screenshots**
The portal to the right is where I threw the items in, and the one in the box is where they exited.
![image](https://user-images.githubusercontent.com/31721920/174427125-dac5b0c5-818e-409e-b58e-f2ef768f9238.png)

**Comment by SuperMartijn642** [comment] 2022-06-18 09:02
I think you are misunderstanding how Wormhole's portals work. You cannot connect portals. A portal simply teleports you (or any entity) to the location you specified with the target definition device.

**Comment by vizthex123** [comment] 2022-06-18 18:48
> I think you are misunderstanding how Wormhole's portals work. You cannot connect portals. A portal simply teleports you (or any entity) to the location you specified with the target definition device.

Other portal mods I've used move you smoothly, but either way it's just annoying how things are 3 blocks away from the portal frame. It should be directly in front of the portal.

**Comment by SuperMartijn642** [comment] 2022-06-18 19:30
Like I said, it will teleport any entities to exactly where you specify with the target definition device. There's is no connection between portals.
If you want it to teleport you directly in front of another portal, you'll have to specify that position with the target definition device.

**Comment by SuperMartijn642** [comment] 2022-06-25 08:55
Closing this, as the mod works as intended. You don't seem to understand how the mod works.

**Closed as completed by SuperMartijn642** 2022-06-25 08:55 UTC
Labels: bug
