### ISSUE TITLE
[Bug] Config not saving

### ISSUE THREAD

**Issue by vizthex123** [SuperMartijn642/Wormhole#32] opened 2022-07-11 08:18 UTC
**Version Info**
- Minecraft: 1.18.2
- Wormhole: 1.1.10

**Description of the Bug**
The config file doesn't save when changed

**Steps to Reproduce**
1) Edit the config
2) Reload the game

**Screenshots**
N?A

Game log:
[latest.log](https://github.com/SuperMartijn642/Wormhole/files/9082071/latest.log)

**Comment by SuperMartijn642** [comment] 2022-07-12 13:44
I cannot reproduce the issue. What entries in the config are you changing and to what values?

**Comment by vizthex123** [comment] 2022-07-14 05:14
I changed almost all of it, here's my config:
[wormhole-common.txt](https://github.com/SuperMartijn642/Wormhole/files/9108667/wormhole-common.txt)


Had to make it a text file for GitHub to accept it.

**Comment by SuperMartijn642** [comment] 2022-07-14 10:00
Thank you, the problem seems to be the spaces in the table names.
```diff
- [Power Consumption]
+ ["Power Consumption"]
```
This should already have been fixed in my config library version 1.1.4. It will regenerate the values of tables which had spaces in their name, after that you should be able to edit those values just fine.
What version of my config library are you using?

**Comment by vizthex123** [comment] 2022-07-17 23:44
1.1.6, had this config since I downloaded the mod, so that might be why. Guess I can manually copy the changes over.

Edit: Tested it, didn't work. Gonna delete the config and see if that fixes it.

Edit 2: Fixed it, regenerated the config and re-did my changes. Gonna close the issue now.

**Closed as completed** 2022-07-18 00:09 UTC
Labels: bug
